name: Deploy to production

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@master
        - name: Publish to Registry
          uses: elgohr/Publish-Docker-Github-Action@master
          with:
            name: vivishadow/vgo
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}